# 部署前的基础路径修改
baseurl      = "xiaocong.site"
languageCode = "zh-cn"
title        = "小葱的学术基站"
timeZone = "Asia/Shanghai"
# 主题语言支持
# 设置为中文以匹配你的内容
defaultContentLanguage = "zh-cn"

# 重要：对于中文环境，必须开启 CJK 支持
# 这样 .Summary 和 .WordCount 才能在中文下正常工作
hasCJKLanguage = true

# Disqus 短代码（若不使用评论系统可保持原样或注释掉）
disqusShortname = ""

[pagination]
    pagerSize = 5
[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"